services:
  db:
    image: postgres:16
    container_name: noteflow-db
    environment:
      POSTGRES_DB: noteflow
      POSTGRES_USER: churrupaquito
      POSTGRES_PASSWORD: sevoya
    ports:
      - "5432:5432"
    volumes:
      - noteflow_pgdata:/var/lib/postgresql/data

volumes:
  noteflow_pgdata: